apiVersion: apps/v1
kind: Deployment
metadata:
  name: enowshop-api-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enowshop-api-user
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
      labels:
        app: enowshop-api-user
    spec:
      containers:
        - name: enowshop-api-user
          image: gcr.io/enowhop/enowshop-api-user:122
          ports:
              - containerPort: 8080
          env:
            - name: A-POSTGRES_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: A-POSTGRES_DATABASE_URL
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_REALMS
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: KEYCLOAK_REALMS
            - name: KEYCLOAK_CLIENT_ID_USERS
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: KEYCLOAK_CLIENT_ID_USERS
            - name: KEYCLOAK_CLIENT_SECRET_USERS
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: KEYCLOAK_CLIENT_SECRET_USERS
            - name: KEYCLOAK_CLIENT_SECRET_ADMIN_CLI
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: KEYCLOAK_CLIENT_SECRET_ADMIN_CLI
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: PUBLIC_KEY
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: SENDGRID_API_KEY
            - name: ORDER_URL
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: ORDER_URL