apiVersion: apps/v1
kind: Deployment
metadata:
  name: enowshop-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enowshop-api-user
  template:
    metadata:
      labels:
        app: enowshop-api-user
    spec:
      containers:
      - name: enowshop-api-user
        image: gcr.io/enowhop/enowsho-api-user:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: enowshop-api-user-service
spec:
  selector:
    app: enowshop-api-user
  ports:
  - port: 80
    targetPort: 9090
  type: LoadBalancer