apiVersion: apps/v1
kind: Deployment
metadata:
  name: enowshop-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
      - name: api-user
        image: gcr.io/enowhop/enowshop-api-user:latest
        ports:
        - containerPort: 8080
