apiVersion: apps/v1
kind: Deployment
metadata:
  name: enowshop-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enowshop-api-user
  template:
    metadata:
      labels:
        app: enowshop-api-user
    spec:
      containers:
      - name: enowshop-api-user
        image: gustavobkdev/goserver:lastest 
        ports:
        - containerPort: 9090
