apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: gustavobkdev/goserver:lastest 
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: goserver-servive
spec:
  selector:
    app: goserver
  ports:
  - port: 80
    targetPort: 9090
  type: LoadBalancer