apiVersion: apps/v1
kind: Deployment
metadata:
  name: enowshop-api-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enowshop-api-user
  template:
    metadata:
      labels:
        app: enowshop-api-user
    spec:
      containers:
        - name: enowshop-api-user
          image: gcr.io/enowhop/enowshop-api-user:106
          ports:
              - containerPort: 8080
          env:
            - name: A-POSTGRES_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: A-POSTGRES_DATABASE_URL
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_REALMS
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: KEYCLOAK_REALMS
            - name: KEYCLOAK_CLIENT_ID_USERS
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: KEYCLOAK_CLIENT_ID_USERS
            - name: KEYCLOAK_CLIENT_SECRET_USERS
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: KEYCLOAK_CLIENT_SECRET_USERS
            - name: KEYCLOAK_CLIENT_SECRET_USER_ADMIN_CLI
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: KEYCLOAK_CLIENT_SECRET_USER_ADMIN_CLI
            - name: KEYCLOAK_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: api-user-secrets
                  key: PUBLIC_KEY